#!/usr/bin/env python
# coding=utf-8
# author=dave
# create=20150408
import smtplib
from email.mime.text import MIMEText


def output_init(domain):
    file_name = "./reports/fuzz_" + domain + ".html"
    file_object = open(file_name, 'w')
    start_content = '''
<!DOCTYPE html>
<!-- author: dave -->
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>%s - FuzSub </title>
    <link href="./fuzsub_tmp/app.css" rel="stylesheet">
    <style>
      [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
        display: none !important;
      }
      body {
          font-family: Microsoft YaHei !important;
          background-color: #e8e8e8;
          color: #000000;
      }
      header {
        background: #151515;
        border-top: 0px solid #ffc616;
        border-bottom: 3px solid #ffffff;
      }
      a {
        color: #969696;
      }
    </style>
    <script type="text/javascript" src="fuzsub_tmp/jquery.js"></script>
    <script type="text/javascript">
    window.onload=function(){
        $("#detail").append("   Count: " + $(".domain-ip-list").length);
    }
    </script>
  </head>
  <body class="ng-scope" data-feedly-mini="yes">
    <header>
      <div class="container">
        <div class="row">
          <div class="logo">
            <a href="http://www.davex.pw/" target="_blank">
              <img src="./fuzsub_tmp/fuzsub_logo.png" alt="fuzsub logo">
            </a>
          </div>
          <h1 class="hidden-xs" style="color: #c62011">>_ Fuzz Sub-domain</h1>
          <h4 style="color: #B51D0F"><p id="detail">Target:  %s  </p></h4>
          <h2 class="sponsored hidden-xs" style="color: #981C00">Page Generated by <a href="http://www.davex.pw/" style="color: #c62011">FuzSub</a></h2>
        </div>
        <div class="row">
        </div>
      </div>
    </header>
    <section class="">
      <div class="container">
        <div class="row">
          <div ng-show="hasResults" class="col-md-12">

              <table class="table table-hover search-results" id="table">
                  <thead>
                      <tr>
                          <th class="hidden-xs">
                              <a ng-click="sortResults(&#39;Sub-domain&#39;)">
                                  Sub-domain
                              </a>
                          </th>
                          <th>
                              <a ng-click="sortResults(&#39;IP-List&#39;)">
                                  IP List
                              </a>
                          </th>
                          <th class="hidden-xs">
                              <a ng-click="sortResults(&#39;Category&#39;)">
                                  Category
                              </a>
                          </th>
                      </tr>
                  </thead>
                  <tbody>
    ''' % (domain, domain)
    file_object.write(start_content)
    file_object.close()


def output_finished(domain):
    file_name = "./reports/fuzz_" + domain + ".html"
    file_object = open(file_name, 'a')
    end_content = '''
                  </tbody>
              </table>

          </div>
        </div><!-- ./row -->
      </div><!-- ./container -->
    </section>
  </body>
</html>
 '''
    file_object.write(end_content)
    file_object.close()
    print '\n[+] Results the save path: %s' % file_name
    send_an_mail(domain)


def send_an_mail(domain):
    sender = 'Your Email Address[Send]'
    receiver = 'Your Email Address[Receive]'
    subject = '[FuzSub] Fuzz Domain: %s Finished' % domain
    smtp_server = 'Your Email SMTP Server'
    username = 'Your Email Address'
    password = 'Your Email Password'

    exact_time = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))
    msg = MIMEText('''
    <p>Hi!</p>

    <p>The Mission Fuzzing qq.com Finished at %s.</p>

    <p>If You Have Any Problem, You Can Send Me An E-Mail or Visit Github.</p>

    <strong>GitHub:</strong>
    <a href="https://github.com/Captain-D/FuzSub" title="GitHub">@Captain-D</a>

    <p>FuzSub</p>

    ''' % exact_time, "html", 'utf-8')
    msg['Subject'] = subject

    if "@" in sender and receiver:
        smtp = smtplib.SMTP()
        smtp.connect(smtp_server)
        smtp.login(username, password)
        smtp.sendmail(sender, receiver, msg.as_string())
        smtp.quit()


def output_add(sub_domain, ip_list, category, domain):
    file_name = "./reports/fuzz_" + domain + ".html"
    file_object = open(file_name, 'a')
    mid_content = '''
                      <tr>
                          <td class="hidden-xs owner" bind-once="result.owner">
                              <a href="http://%s" target="_blank">
                                  %s
                              </a>
                          </td>
                          <td class="domain-ip-list">
                              <p class="description" bind-attr-once="{title: result.description}" bind-once="result.description" title="jQuery Mobile Framework">
                                  %s
                              </p>
                          </td>
                          <td class="hidden-xs owner" bind-once="result.owner">
                              %s
                          </td>
                      </tr>
    ''' % (sub_domain, sub_domain, ip_list, category)
    file_object.write(mid_content)
    file_object.close()